#!/usr/bin/env python
# -*- coding: utf-8 -*

from bs4 import BeautifulSoup

html_doc = "html doc to scrape"

soup = BeautifulSoup(html_doc, 'html.parser')

print(soup.prettify()).encode('utf-8')

for link in soup.find_all('a'):
    print(link.get('href'))

print soup.title
